version: '3.8'

services:
  db:
    image: ankane/pgvector:latest
    container_name: db_employee
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_employee
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432" # Sử dụng biến môi trường hoặc mặc định 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d db_employee"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres_data: